name: diffusion
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - aiohttp<=3.8
  - chardet
  - dm-haiku
  - datasets
  - wandb
  - einops
  - ftfy
  - numpy
  - optax
  - regex
  - Pillow
  - pytorch
  - torchvision
  - tqdm
  - pip:
    - coax
    - ./CLIP_JAX